# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/Vivado/Project/net_engine_ip/net_engine_ip.srcs/sources_1/ip/master_fifo_out/master_fifo_out.xci
# IP: The module: 'master_fifo_out' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Vivado/Project/net_engine_ip/net_engine_ip.gen/sources_1/ip/master_fifo_out/master_fifo_out.xdc
# XDC: The top module name and the constraint reference have the same name: 'master_fifo_out'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/Vivado/Project/net_engine_ip/net_engine_ip.gen/sources_1/ip/master_fifo_out/master_fifo_out_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'master_fifo_out'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: D:/Vivado/Project/net_engine_ip/net_engine_ip.srcs/sources_1/ip/master_fifo_out/master_fifo_out.xci
# IP: The module: 'master_fifo_out' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Vivado/Project/net_engine_ip/net_engine_ip.gen/sources_1/ip/master_fifo_out/master_fifo_out.xdc
# XDC: The top module name and the constraint reference have the same name: 'master_fifo_out'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/Vivado/Project/net_engine_ip/net_engine_ip.gen/sources_1/ip/master_fifo_out/master_fifo_out_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'master_fifo_out'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
