# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Vivado/Project/net_engine_ip/net_engine_ip.srcs/sources_1/ip/floating_point_0_1/floating_point_0.xci
# IP: The module: 'floating_point_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Vivado/Project/net_engine_ip/net_engine_ip.gen/sources_1/ip/floating_point_0_1/floating_point_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'floating_point_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: d:/Vivado/Project/net_engine_ip/net_engine_ip.srcs/sources_1/ip/floating_point_0_1/floating_point_0.xci
# IP: The module: 'floating_point_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Vivado/Project/net_engine_ip/net_engine_ip.gen/sources_1/ip/floating_point_0_1/floating_point_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'floating_point_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
